spring:
  application:
    name: ${APP_NAME:spring-ai-project}

  ai:
    model:
      chat: openai
    openai:
      chat:
        model: ai/gemma3
      base-url: http://localhost:12434/engines/v1
      api-key: docker