spring:
  application:
    name: ${APP_NAME:spring-ai-project}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    ollama:
      chat:
        model: llama3.2
    chat:
      client:
        enabled: false