spring:
  application:
    name: ${APP_NAME:spring-ai-project}

  ai:
    model:
      chat: bedrock-converse
    bedrock:
      aws:
        region: ${AWS_REGION}
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      converse:
        chat:
          model: ${AWS_BEDROCK_MODEL_ID}